const IMG = 'Images Sites Macrinère';

export const products = [
  { id: 'masque-hydratant-argan', slug: 'masque-hydratant-argan', name: 'Masque Hydratant Argan', tag: 'INTENSE', price: 225, image: `${IMG}/Produit 1.jpg`, images: [`${IMG}/Produit 1.jpg`, `${IMG}/Produit 2.jpg`, `${IMG}/Produit 3.jpg`], descriptionShort: "Ma Crinière révolutionne l'hydratation capillaire : ce masque à l'argan offre une nutrition intense et un confort durable. Sa formule enrichie en huile d'argan marocaine pénètre la fibre pour des pointes repulpées et une chevelure brillante. Un soin profond sans effet gras, idéal pour les cheveux secs et bouclés.", descriptionLong: "Notre masque hydratant à l'huile d'argan pénètre en profondeur pour réparer et nourrir les pointes abîmées. Formule riche en actifs naturels, sans sulfates ni silicones, idéale pour les cheveux secs et bouclés. Laisser poser 5 à 10 minutes une à deux fois par semaine pour un résultat optimal. Testé sous contrôle dermatologique.", features: ["Huile d'argan", 'Sans sulfates', 'Vegan', '250 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '15 × 5 cm', Couleur: 'Doré', Poids: '250 ml' }, stock: 24 },
  { id: 'shampooing-charbons', slug: 'shampooing-charbons', name: 'Shampooing Charbons', tag: 'PURIFIANT', price: 185, image: `${IMG}/Produit 2.jpg`, images: [`${IMG}/Produit 2.jpg`, `${IMG}/Produit 1.jpg`], descriptionShort: "Le Shampooing Charbons Ma Crinière purifie en douceur : le charbon actif élimine les résidus et l'excès de sébum tout en respectant l'équilibre du cuir chevelu. Un geste fraîcheur pour des racines légères et des longueurs respirables. À utiliser en cure ou en alternance avec votre shampooing quotidien.", descriptionLong: "Le charbon actif d'origine naturelle absorbe les impuretés et l'excès de sébum sans agresser. Formule sans parabènes, pH équilibré. Parfait pour une utilisation hebdomadaire ou en cure détox. Masser le cuir chevelu puis rincer abondamment. En alternance avec un shampooing doux pour préserver l'hydratation des pointes.", features: ['Charbon actif', 'Purifiant', 'Sans parabènes', '200 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '14 × 4,5 cm', Couleur: 'Noir', Poids: '200 ml' }, stock: 18 },
  { id: 'gloss-lavande', slug: 'gloss-lavande', name: 'Gloss Lavande', tag: 'BRILLANCE', price: 145, promo: { percent: 10, label: '-10%' }, image: `${IMG}/Produit 3.jpg`, images: [`${IMG}/Produit 3.jpg`], descriptionShort: "Le Gloss Lavande apporte brillance et légèreté : l'extrait de lavande de Provence gaine la fibre et laisse un fini soyeux sans alourdir. Reflets lumineux et senteur apaisante pour une chevelure visiblement plus douce. À appliquer sur longueurs et pointes après le coiffage.", descriptionLong: "Ce gloss capillaire légèrement teinté à l'extrait de lavande nourrit la cuticule et renforce l'éclat. Sans silicone, il ne pèse pas sur les boucles. Appliquer une noisette sur les longueurs essorées ou sur cheveux secs pour un voile de brillance. Parfum délicat et tenue longue durée.", features: ['Lavande', 'Brillance', 'Sans silicone', '150 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '12 × 4 cm', Couleur: 'Lavande', Poids: '150 ml' }, stock: 30 },
  { id: 'soins-solaires', slug: 'soins-solaires', name: 'Soins Solaires', tag: 'PROTECTION', price: 255, image: `${IMG}/Produit 4.jpg`, images: [`${IMG}/Produit 4.jpg`], descriptionShort: "Soins Solaires protège et hydrate : ce spray invisible forme un bouclier contre les UV et la sécheresse. Votre crinière garde souplesse et éclat même en plein soleil. À vaporiser avant l'exposition et renouveler pour une protection continue tout l'été.", descriptionLong: "Notre formule combine filtres UV et actifs hydratants pour limiter la déshydratation et les dommages du soleil. Résistant à l'eau, le spray tient lors des baignades. Vaporiser sur cheveux secs ou mouillés, en évitant le cuir chevelu. Idéal pour les vacances et les journées en extérieur.", features: ['Protection UV', 'Hydratant', "Résistant à l'eau", '200 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '14 × 4 cm', Couleur: 'Transparent', Poids: '200 ml' }, stock: 12 },
  { id: 'huile-capillaire-cocotte', slug: 'huile-capillaire-cocotte', name: 'Huile Capillaire Cocotte', tag: 'NOURRISTANT', price: 195, image: `${IMG}/Hero Produits.jpg.jpg`, images: [`${IMG}/Hero Produits.jpg.jpg`], descriptionShort: "L'Huile Capillaire Cocotte gaine et protège : un blend d'huiles précieuses (argan, coco, jojoba) nourrit les pointes sans les alourdir. Fini satiné et protection anti-fourches au quotidien. En leave-in sur les pointes ou en bain d'huile avant le shampooing.", descriptionLong: "Notre mélange d'huiles 100 % naturelles pénètre la fibre pour restaurer l'équilibre hydrolipidique. Utilisation leave-in : une à deux gouttes sur les pointes après coiffage. En bain d'huile : appliquer généreusement, laisser poser 30 min à 1 h sous serviette chaude, puis shampooiner. Sans rinçage à l'eau froide.", features: ['Multi-huiles', 'Pointes', 'Sans rinçage', '100 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '8 × 3 cm', Couleur: 'Ambre', Poids: '100 ml' }, stock: 20 },
  { id: 'coiffant-eclat-karite', slug: 'coiffant-eclat-karite', name: 'Coiffant Éclat Karité', tag: 'BOUCLES', price: 165, image: `${IMG}/Produit 6.jpg`, images: [`${IMG}/Produit 6.jpg`], descriptionShort: "Le Coiffant Éclat Karité définit et nourrit les boucles : la texture fondante au beurre de karité africain sculpte les boucles sans les alourdir. Souplesse, éclat et tenue sans effet collant. Parfait pour définir les boucles naturelles ou raviver une mise en pli.", descriptionLong: "Le beurre de karité certifié apporte une nutrition ciblée tout en fixant la forme des boucles. Appliquer sur cheveux essorés, mèche par mèche, puis laisser sécher à l'air ou au diffuseur. Sans cruauté, testé sur tous types de boucles. Résultat visible : boucles définies, douces et brillantes.", features: ['Beurre de karité', 'Définition', 'Sans cruauté', '200 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '14 × 4,5 cm', Couleur: 'Ivoire', Poids: '200 ml' }, stock: 22 },
  { id: 'serum-reparateur', slug: 'serum-reparateur', name: 'Sérum Réparateur', tag: 'RÉPARATION', price: 210, image: `${IMG}/serum reparateur.jpg`, images: [`${IMG}/serum reparateur.jpg`], descriptionShort: "Le Sérum Réparateur renforce et illumine : concentré en kératine et actifs réparateurs, il colmate les écailles et redonne de l'éclat aux cheveux abîmés ou colorés. Compatible coloration, il protège la fibre sans alourdir. À appliquer sur longueurs et pointes après chaque shampooing.", descriptionLong: "Notre formule color-safe pénètre la fibre pour restaurer la résistance et la brillance. Idéal après coloration, brushing ou exposition au soleil. Application sur cheveux essorés (1 à 2 pressions) ou sur cheveux secs pour un fini lissant. Ne rince pas. Résultat immédiat : cheveux plus doux et lumineux.", features: ['Kératine', 'Réparation', 'Color-safe', '50 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '10 × 3 cm', Couleur: 'Incolore', Poids: '50 ml' }, stock: 15 },
  { id: 'baume-hydratant', slug: 'baume-hydratant', name: 'Baume Hydratant', tag: 'HYDRATATION', price: 175, image: `${IMG}/Image Produit 8.jpg`, images: [`${IMG}/Image Produit 8.jpg`], descriptionShort: "Le Baume Hydratant Ma Crinière hydrate 24 h sans rinçage : texture légère qui pénètre instantanément sans film gras. Toucher doux, chevelure disciplinée et protégée des agressions du quotidien. Parfait en fin de routine pour sceller l'hydratation.", descriptionLong: "Notre baume sans rinçage combine des actifs hydratants à libération prolongée. Appliquer une noisette sur les longueurs et pointes après le coiffage, sur cheveux secs ou humides. Formule vegan, sans silicone. Idéal pour les cheveux secs à très secs en entretien quotidien.", features: ['Sans rinçage', 'Hydratation 24h', 'Vegan', '150 ml'], specs: { Marque: 'Ma Crinière', Dimensions: '12 × 4 cm', Couleur: 'Blanc nacré', Poids: '150 ml' }, stock: 28 },
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug);
}

export function getProductById(id) {
  return products.find((p) => p.id === id);
}

export function getProductPrice(product) {
  if (product.promo) {
    return Math.round(product.price * (1 - product.promo.percent / 100));
  }
  return product.price;
}

export function getSimilarProducts(productId, limit = 4) {
  const product = getProductById(productId);
  if (!product) return products.slice(0, limit);
  return products.filter((p) => p.id !== productId).slice(0, limit);
}
